services:
  - type: web
    name: event-pass-generator
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn eventpass_backend.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
